### ISSUE TITLE
Dynamic connect flow

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-identity-service-example#2]
**Summary:**  
`At the moment we are providing the option for end-user to enroll, after passing the authentication flow inside the Salt Edge Authenticator. What if customer has already authenticated himself in web application? In this case, it's possible to generate personal QR code for the user, where will be stored sort of "connect_query", an ID which will recognize end-user. Hence, with this update user will have a choice - either use general QR code/Deep Link before he is authenticated into system and user passes authentication inside Salt Edge Authenticator app, or with dynamic QR code/Deep Link end-user will first login in web app, where for him will be generated personalized QR code/Deep Link, and after scan/access > user instantly passes enrollment. With this update we will add to the solution even more universality.`

**Task:**  
- [x] Update 2 applications:
  - iOS issue: https://github.com/saltedge/sca-authenticator-ios/issues/34
  - Android issue: https://github.com/saltedge/sca-authenticator-android/issues/56
- [x] Update the Identity Service code accordingly
- [x] Update API documentation with new logic explanation
- [x] Update WIKI with new flow, add links @AlexLobaciov 

**Expected behavior:**  
- When end-user receives from service provider the personalized QR code/Deep link, which stores `connect_query`, and scans/accesses it via Salt Edge Authenticator, it should be stored in `POST/connection` API request. As a result, end-user is instantly enrolled

___
Thanks!

**Comment by AlexLobaciov** [comment]
Done.
