### ISSUE TITLE
Geolocation & Authorization type in API and IS Example

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-identity-service-example#55]
**Summary:**  
In order for payment service provider to increase the accuracy of "Transaction Risk Analysis", it is required to share Customer's "Geolocation" and "Authorization type" in POST request, when providing Customer response on authorized action.

**Task:**  
- [ ] Update API documentation with "Geolocation" parameter [HERE](https://github.com/saltedge/sca-identity-service-example/blob/master/docs/IDENTITY_SERVICE_API.md#request-example-1)
- [ ] Update existing Identity service example with logic to receive and display somewhere these parameters
- [ ] Update Terms of Service (@AlexLobaciov) with Legal team

Add following description to API Documentation:  
Mobile GPS data information is collected (optionally) for accurate Transaction Risk Analysis (TRA). Service provider can check whether the user’s handset is in an unusual location and act on that information. GPS tracking is a reliable way of monitoring the movements of an individual because they usually have their phones on them and thus provides valuable data that can be used in fraud detection. The information gained from the app is used to determine whether the location of application from which action was initiated aligns with the location of the individual’s mobile device when action is authorized.
